[3.4] [Modlog] Check if guild is unavailable (#5647)
fix for  AttributeError: 'NoneType' object has no attribute 'guild_permissions'
(cherry picked from commit 485e6837ca089f3a906e5222ce8a58a5e09ba6ba)

Co-authored-by: Candy <28566705+mina9999@users.noreply.github.com>