added missing period
When testing 3.5 I tried to list all ignored channels and got an error which referenced `AttributeError: 'Core' object has no attribute 'bot_ignored_cache'` bot_ignored_cache is only mentioned here and appears to be a typo. Which I've tested locally and fixed the error.